title: Cen Jingcheng's Homepage
page-top-title: Cen Jingcheng
top-section-bg-text: Be what you wanna be
home-subtitle: Cen Jingcheng&ensp;|&ensp;岑景成
copyright-text: '&copy; Cen Jingcheng 2023-2025. All Rights Reserved.'
